travis:
  secure:
    BINSTAR_TOKEN: N1WVncKuDxkEJXZ3idO00lHqmD7RgCHNJAjQmf9Cttv40OYTEz5MWdSM566Xix2DAXtZ77tf1Bfxk7DNKsFwKwA1nfZxEy4cLwntcWcyYaDd66IbMRfBNfE2tEICi4kQg/Z+bL1n5FA5a51bsQ9IJO4WXc71Pmw8dFMhuMFHyAPRcj+IBjVwB6/XP4qlNzJHaBMzEkpJt8RPptlws+LH+VsQ67M9utqrsqcaNSsHfr2MxIe/+//c16yt+iYV43meQ3WnNXg0SavKtFI6gz1cPjwdM8r7SK/hpTtDV8F9gIizSTT/loLDYIzYKijtJVG0UTI1es4cIhaJ1OXMentYpyTcfjGnr5+Dmm8eW5zq15RR6CXno5kD4Yy7ODTS9nDfZiAuZOeU/5G4b1lsDTnyQUTQMGJjd1ZJpmNYaugVKvAQi/9feLfqzH7Y2ragfSbstvF319/6AWog/aSYt4lxHcn5aJBrmIYqKAu8uNc1uo2mqN4MpgurxWkTHrTQqn24HUYxbva7sw03N6bS9mP/5cLdzqbknAHrj/j0z4KLMXeTCeocmXS2+wwe5EDWTwqARQEyak1Q8YVsahMuYMfeuAMvrksi0Xhq/BZlu0JdSSx7VA7qOk7wT3GzZ6AIjwhWi2H0W4qrZLP9Wn888Xq0uV0bT43f7MQFjwPQb49YOes=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
